program_CXX_SRC += $(wildcards src/*.cpp)
program_INCLUDE += $(wildcards src/include/*.h)
program_CXX_OBJS += $(program_CXX_SRC:.cpp=.o)
program_NAME    += BinaryTree
all: $(program_CXX_OBJS)
    $(Link.cc) $() -o $(program_NAQ
    
